/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import primafibonacci.Execute;

/**
 *
 * @author MUHAMMAD BIN ZANDRA
 */
public class Fibonacci extends javax.swing.JInternalFrame {

    /**
     * Creates new form Fibonacci
     */
    public Fibonacci() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fibodekstop = new javax.swing.JDesktopPane();
        fibo_batas = new javax.swing.JTextField();
        fibo_hasil = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        fibodekstop.setBackground(new java.awt.Color(204, 204, 204));

        fibo_batas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fibo_batasActionPerformed(evt);
            }
        });

        jButton1.setText("Proses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("angka batas");

        jLabel4.setText("hasil");

        fibodekstop.setLayer(fibo_batas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fibodekstop.setLayer(fibo_hasil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fibodekstop.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fibodekstop.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fibodekstop.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout fibodekstopLayout = new javax.swing.GroupLayout(fibodekstop);
        fibodekstop.setLayout(fibodekstopLayout);
        fibodekstopLayout.setHorizontalGroup(
            fibodekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fibodekstopLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(fibodekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(fibodekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fibo_hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(fibo_batas, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
        fibodekstopLayout.setVerticalGroup(
            fibodekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fibodekstopLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(fibodekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fibo_batas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGroup(fibodekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fibodekstopLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(fibo_hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fibodekstopLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(52, 52, 52))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fibodekstop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fibodekstop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Execute ex = new Execute();
        int c = Integer.parseInt(fibo_batas.getText());
        
        String Hasil = ex.Fibo(c);
        fibo_hasil.setText(Hasil);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fibo_batasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fibo_batasActionPerformed
        // TODO add your handling code here:
        
        fibo_batas.getText();
    }//GEN-LAST:event_fibo_batasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fibo_batas;
    private javax.swing.JLabel fibo_hasil;
    private javax.swing.JDesktopPane fibodekstop;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
