/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import primafibonacci.Execute;

/**
 *
 * @author MUHAMMAD BIN ZANDRA
 */
public class Prima extends javax.swing.JInternalFrame {

    /**
     * Creates new form Prima
     */
    public Prima() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        primadekstop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        cekPrima = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ketPrima = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        primadekstop.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("prima");

        cekPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekPrimaActionPerformed(evt);
            }
        });

        jButton1.setText("cek");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("bil");

        jLabel3.setText("hasl");

        primadekstop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        primadekstop.setLayer(cekPrima, javax.swing.JLayeredPane.DEFAULT_LAYER);
        primadekstop.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        primadekstop.setLayer(ketPrima, javax.swing.JLayeredPane.DEFAULT_LAYER);
        primadekstop.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        primadekstop.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout primadekstopLayout = new javax.swing.GroupLayout(primadekstop);
        primadekstop.setLayout(primadekstopLayout);
        primadekstopLayout.setHorizontalGroup(
            primadekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primadekstopLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(primadekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(primadekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cekPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ketPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        primadekstopLayout.setVerticalGroup(
            primadekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(primadekstopLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(primadekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cekPrima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGroup(primadekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(primadekstopLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ketPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(primadekstopLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(primadekstop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(primadekstop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cekPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekPrimaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cekPrimaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Execute pr = new Execute();
        String nilai = cekPrima.getText();
        
        int ambil = Integer.parseInt(nilai);
        String hasil = pr.primaaa(ambil);
        
        ketPrima.setText(hasil);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cekPrima;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel ketPrima;
    private javax.swing.JDesktopPane primadekstop;
    // End of variables declaration//GEN-END:variables
}
